"""Added project batch tables

Revision ID: 26c42d0d48f0
Revises: ba748dd8da33
Create Date: 2024-08-17 23:45:19.926761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26c42d0d48f0'
down_revision: Union[str, None] = 'ba748dd8da33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
