"""Added enabled field

Revision ID: 3137b8f27851
Revises: 94a72fb4cdd4
Create Date: 2024-09-12 23:45:55.347784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3137b8f27851'
down_revision: Union[str, None] = '94a72fb4cdd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('enabled', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'enabled')
    # ### end Alembic commands ###
