"""Added code metrics table

Revision ID: 4b04a6ff56d7
Revises: e02dc5223025
Create Date: 2024-09-05 19:51:07.164432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b04a6ff56d7'
down_revision: Union[str, None] = 'e02dc5223025'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('batches', sa.Column('last_patch', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('batches', 'last_patch')
    # ### end Alembic commands ###
