"""add is_processed field

Revision ID: 5d6bad884aef
Revises: c7bb4e36e4a8
Create Date: 2024-08-22 14:34:21.428609

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '5d6bad884aef'
down_revision: Union[str, None] = 'c7bb4e36e4a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('batches', sa.Column('is_processed', sa.Boolean(), nullable=False, server_default='False'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('batches', 'is_processed')
    # ### end Alembic commands ###
