"""Added last_patch and last_branch to batches

Revision ID: 94a72fb4cdd4
Revises: 4b04a6ff56d7
Create Date: 2024-09-05 20:10:29.435215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94a72fb4cdd4'
down_revision: Union[str, None] = '4b04a6ff56d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('batches', sa.Column('last_branch', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('batches', 'last_branch')
    # ### end Alembic commands ###
