"""Added processed flag

Revision ID: c6fab014f70e
Revises: 74530e0c5061
Create Date: 2024-08-12 15:31:30.269665

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c6fab014f70e'
down_revision: Union[str, None] = '74530e0c5061'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_patches', sa.Column('processed', sa.Boolean(), nullable=False,
                                               server_default=sa.sql.expression.false()))
    op.add_column('project_patches', sa.Column('metric_collected', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_patches', 'metric_collected')
    op.drop_column('project_patches', 'processed')
    # ### end Alembic commands ###
