"""new fields for threads

Revision ID: dbfe150a36fb
Revises: ed8ea3907251
Create Date: 2024-09-02 14:48:52.201596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbfe150a36fb'
down_revision: Union[str, None] = 'ed8ea3907251'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('openai_assistant_threads', sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('openai_assistant_threads', sa.Column('last_user_message_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('openai_assistant_threads', sa.Column('reason', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('openai_assistant_threads', 'reason')
    op.drop_column('openai_assistant_threads', 'last_user_message_at')
    op.drop_column('openai_assistant_threads', 'closed_at')
    # ### end Alembic commands ###
